#!/bin/sh

helpdir="/usr/share/gnome/help/";

title=$1
if [ "x$title" = "x" ]; then
    echo "You must specify a title for the timing run.";
    exit 1;
fi;

mkdir -p "$title";
mkdir -p "$title/_LOGS";
rm -f "$title.times" && touch "$title.times"

for doc in `ls $helpdir`; do
    docdir="$helpdir$doc";
    if [ -d "$docdir" ]; then
	for lang in `ls $docdir`; do
	    langdir="$docdir/$lang";
	    if [ -d "$langdir" ]; then
		docfile="$langdir/$doc.xml";
		outdir="$title/$doc/$lang";
		outfile="$outdir/$doc.xhtml";
		logfile="$title/_LOGS/$doc.$lang.out";
		mkdir -p "$outdir";
		rm -f "$logfile" && touch "$logfile";
		for i in 1 2 3 4 5; do
		    xsltproc --xinclude --timing \
			--stringparam "db.chunk.basename" "$doc" \
			-o "$outfile" \
			../../xslt/docbook/html/db2html.xsl \
			"$docfile" 2>> $logfile;
		done;
		times=`grep 'Running stylesheet and saving result took' \
                    "$logfile" | cut -d' ' -f7 - | sed -e 's/$/+/g'`;
		total=`echo $times 0 | bc`;
		avg=`echo $total / 5 | bc`;
		echo "$doc/$lang  $avg" >> "$title.times";
	    fi;
	done;
    fi;
done;
